### PR TITLE
Install instructions wget, imagemagick in cygwin

### PR DESCRIPTION
**Pull request by atultiwari**

### CODE REVIEW

**Comment by lovasoa** [comment]
I created the wiki page and uploaded all your screenshots
https://github.com/lovasoa/dezoom.sh/wiki/Installation-on-windows

**Comment by lovasoa** [comment]
https://raw.githubusercontent.com/wiki/lovasoa/dezoom.sh/screenshot-0.PNG
https://raw.githubusercontent.com/wiki/lovasoa/dezoom.sh/screenshot-1.PNG
...
https://raw.githubusercontent.com/wiki/lovasoa/dezoom.sh/screenshot-4.PNG

**Comment by lovasoa** [comment]
Maybe you should make _Installation on windows_ section of the readme shorter , and link to the more detailed information with screenshots on the wiki

**Comment by atultiwari** [comment]
Ok. I got your point.. i will add to wiki later tonight

**Comment by atultiwari** [comment]
I have updated the wiki with relevant screenshots. I didn't feel like that I should write click Next - Next 9 times, so added gif to summarize the whole process. Hope it might be useful.

**Comment by lovasoa** [comment]
Thank you very much for your good work ! :+1: 

In the future, please prefer pull requests over direct modifications of the repo. It allows us to discuss of the changes before integrating them. You will then be able to merge your pull requests yourself since you are now a collaborator of this project.

I think information on how to use a proxy should be either on another wiki page or in the README, but not in the windows instructions page, since its not specific to windows.

**Comment by lovasoa** [comment]
I'm closing this since you have already committed the changes directly to `master`, but feel free to comment further.

**Pull request closed without merging**
